version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "saihaj"
    # Specify labels for npm pull requests
    labels:
      - "npm dependencies"
